// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.DataAccess;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(MyDatabase))]
    [Migration("20240814153641_AddNewDataBase")]
    partial class AddNewDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication2.DataAccess.Models.CourseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Name = "Multimedia"
                        },
                        new
                        {
                            Id = 1002,
                            Name = "Principles of Computer Networks"
                        },
                        new
                        {
                            Id = 1003,
                            Name = "Introduction to databases"
                        },
                        new
                        {
                            Id = 1004,
                            Name = "Graphic Evolution and Image Processing"
                        },
                        new
                        {
                            Id = 1005,
                            Name = "Technical English"
                        },
                        new
                        {
                            Id = 1006,
                            Name = "Web Programming"
                        },
                        new
                        {
                            Id = 1007,
                            Name = "Physical Activity"
                        },
                        new
                        {
                            Id = 1008,
                            Name = "Software Applications"
                        },
                        new
                        {
                            Id = 1009,
                            Name = "Advanced Databases"
                        },
                        new
                        {
                            Id = 1010,
                            Name = "Web Server Administration"
                        });
                });

            modelBuilder.Entity("WebApplication2.DataAccess.Models.RegistrationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RegistrationYear")
                        .HasColumnType("int");

                    b.Property<int>("SectionCourseId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("StudentId", "SectionCourseId", "SemesterId", "RegistrationYear");

                    b.HasIndex("SectionCourseId");

                    b.HasIndex("SemesterId");

                    b.ToTable("Registration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RegistrationYear = 2024,
                            SectionCourseId = 1,
                            SemesterId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            RegistrationYear = 2024,
                            SectionCourseId = 1,
                            SemesterId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            RegistrationYear = 2024,
                            SectionCourseId = 1,
                            SemesterId = 1,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            RegistrationYear = 2024,
                            SectionCourseId = 1,
                            SemesterId = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 5,
                            RegistrationYear = 2024,
                            SectionCourseId = 1,
                            SemesterId = 1,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 6,
                            RegistrationYear = 2024,
                            SectionCourseId = 1,
                            SemesterId = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 7,
                            RegistrationYear = 2024,
                            SectionCourseId = 1,
                            SemesterId = 1,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 8,
                            RegistrationYear = 2024,
                            SectionCourseId = 2,
                            SemesterId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 9,
                            RegistrationYear = 2024,
                            SectionCourseId = 2,
                            SemesterId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 10,
                            RegistrationYear = 2024,
                            SectionCourseId = 2,
                            SemesterId = 1,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 11,
                            RegistrationYear = 2024,
                            SectionCourseId = 2,
                            SemesterId = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 12,
                            RegistrationYear = 2024,
                            SectionCourseId = 2,
                            SemesterId = 1,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 13,
                            RegistrationYear = 2024,
                            SectionCourseId = 2,
                            SemesterId = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 14,
                            RegistrationYear = 2024,
                            SectionCourseId = 2,
                            SemesterId = 1,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 15,
                            RegistrationYear = 2024,
                            SectionCourseId = 3,
                            SemesterId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 16,
                            RegistrationYear = 2024,
                            SectionCourseId = 3,
                            SemesterId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 17,
                            RegistrationYear = 2024,
                            SectionCourseId = 3,
                            SemesterId = 1,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 18,
                            RegistrationYear = 2024,
                            SectionCourseId = 3,
                            SemesterId = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 19,
                            RegistrationYear = 2024,
                            SectionCourseId = 3,
                            SemesterId = 1,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 20,
                            RegistrationYear = 2024,
                            SectionCourseId = 3,
                            SemesterId = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 21,
                            RegistrationYear = 2024,
                            SectionCourseId = 3,
                            SemesterId = 1,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 22,
                            RegistrationYear = 2024,
                            SectionCourseId = 4,
                            SemesterId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 23,
                            RegistrationYear = 2024,
                            SectionCourseId = 4,
                            SemesterId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 24,
                            RegistrationYear = 2024,
                            SectionCourseId = 4,
                            SemesterId = 1,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 25,
                            RegistrationYear = 2024,
                            SectionCourseId = 4,
                            SemesterId = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 26,
                            RegistrationYear = 2024,
                            SectionCourseId = 4,
                            SemesterId = 1,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 27,
                            RegistrationYear = 2024,
                            SectionCourseId = 4,
                            SemesterId = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 28,
                            RegistrationYear = 2024,
                            SectionCourseId = 4,
                            SemesterId = 1,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 29,
                            RegistrationYear = 2024,
                            SectionCourseId = 5,
                            SemesterId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 30,
                            RegistrationYear = 2024,
                            SectionCourseId = 5,
                            SemesterId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 31,
                            RegistrationYear = 2024,
                            SectionCourseId = 5,
                            SemesterId = 1,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 32,
                            RegistrationYear = 2024,
                            SectionCourseId = 5,
                            SemesterId = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 33,
                            RegistrationYear = 2024,
                            SectionCourseId = 5,
                            SemesterId = 1,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 34,
                            RegistrationYear = 2024,
                            SectionCourseId = 5,
                            SemesterId = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 35,
                            RegistrationYear = 2024,
                            SectionCourseId = 5,
                            SemesterId = 1,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 36,
                            RegistrationYear = 2024,
                            SectionCourseId = 6,
                            SemesterId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 37,
                            RegistrationYear = 2024,
                            SectionCourseId = 6,
                            SemesterId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 38,
                            RegistrationYear = 2024,
                            SectionCourseId = 6,
                            SemesterId = 1,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 39,
                            RegistrationYear = 2024,
                            SectionCourseId = 6,
                            SemesterId = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 40,
                            RegistrationYear = 2024,
                            SectionCourseId = 6,
                            SemesterId = 1,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 41,
                            RegistrationYear = 2024,
                            SectionCourseId = 6,
                            SemesterId = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 42,
                            RegistrationYear = 2024,
                            SectionCourseId = 6,
                            SemesterId = 1,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 43,
                            RegistrationYear = 2024,
                            SectionCourseId = 7,
                            SemesterId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 44,
                            RegistrationYear = 2024,
                            SectionCourseId = 7,
                            SemesterId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 45,
                            RegistrationYear = 2024,
                            SectionCourseId = 7,
                            SemesterId = 1,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 46,
                            RegistrationYear = 2024,
                            SectionCourseId = 7,
                            SemesterId = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 47,
                            RegistrationYear = 2024,
                            SectionCourseId = 7,
                            SemesterId = 1,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 48,
                            RegistrationYear = 2024,
                            SectionCourseId = 7,
                            SemesterId = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 49,
                            RegistrationYear = 2024,
                            SectionCourseId = 7,
                            SemesterId = 1,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 50,
                            RegistrationYear = 2024,
                            SectionCourseId = 8,
                            SemesterId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 51,
                            RegistrationYear = 2024,
                            SectionCourseId = 8,
                            SemesterId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 52,
                            RegistrationYear = 2024,
                            SectionCourseId = 8,
                            SemesterId = 1,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 53,
                            RegistrationYear = 2024,
                            SectionCourseId = 8,
                            SemesterId = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 54,
                            RegistrationYear = 2024,
                            SectionCourseId = 8,
                            SemesterId = 1,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 55,
                            RegistrationYear = 2024,
                            SectionCourseId = 8,
                            SemesterId = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 56,
                            RegistrationYear = 2024,
                            SectionCourseId = 8,
                            SemesterId = 1,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 57,
                            RegistrationYear = 2024,
                            SectionCourseId = 9,
                            SemesterId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 58,
                            RegistrationYear = 2024,
                            SectionCourseId = 9,
                            SemesterId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 59,
                            RegistrationYear = 2024,
                            SectionCourseId = 9,
                            SemesterId = 1,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 60,
                            RegistrationYear = 2024,
                            SectionCourseId = 9,
                            SemesterId = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 61,
                            RegistrationYear = 2024,
                            SectionCourseId = 9,
                            SemesterId = 1,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 62,
                            RegistrationYear = 2024,
                            SectionCourseId = 9,
                            SemesterId = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 63,
                            RegistrationYear = 2024,
                            SectionCourseId = 9,
                            SemesterId = 1,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 64,
                            RegistrationYear = 2024,
                            SectionCourseId = 10,
                            SemesterId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 65,
                            RegistrationYear = 2024,
                            SectionCourseId = 10,
                            SemesterId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 66,
                            RegistrationYear = 2024,
                            SectionCourseId = 10,
                            SemesterId = 1,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 67,
                            RegistrationYear = 2024,
                            SectionCourseId = 10,
                            SemesterId = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 68,
                            RegistrationYear = 2024,
                            SectionCourseId = 10,
                            SemesterId = 1,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 69,
                            RegistrationYear = 2024,
                            SectionCourseId = 10,
                            SemesterId = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 70,
                            RegistrationYear = 2024,
                            SectionCourseId = 10,
                            SemesterId = 1,
                            StudentId = 7
                        });
                });

            modelBuilder.Entity("WebApplication2.DataAccess.Models.SectionCourseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("courseId");

                    b.ToTable("SectionCourse");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new TimeSpan(0, 13, 0, 0, 0),
                            SectionId = 1,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0),
                            TeacherId = 1,
                            courseId = 1001
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            SectionId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            TeacherId = 2,
                            courseId = 1002
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new TimeSpan(0, 13, 0, 0, 0),
                            SectionId = 1,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0),
                            TeacherId = 3,
                            courseId = 1003
                        },
                        new
                        {
                            Id = 4,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            SectionId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            TeacherId = 4,
                            courseId = 1004
                        },
                        new
                        {
                            Id = 5,
                            EndTime = new TimeSpan(0, 13, 0, 0, 0),
                            SectionId = 1,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0),
                            TeacherId = 5,
                            courseId = 1005
                        },
                        new
                        {
                            Id = 6,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            SectionId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            TeacherId = 1,
                            courseId = 1006
                        },
                        new
                        {
                            Id = 7,
                            EndTime = new TimeSpan(0, 13, 0, 0, 0),
                            SectionId = 1,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0),
                            TeacherId = 2,
                            courseId = 1007
                        },
                        new
                        {
                            Id = 8,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            SectionId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            TeacherId = 3,
                            courseId = 1008
                        },
                        new
                        {
                            Id = 9,
                            EndTime = new TimeSpan(0, 13, 0, 0, 0),
                            SectionId = 1,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0),
                            TeacherId = 4,
                            courseId = 1009
                        },
                        new
                        {
                            Id = 10,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            SectionId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            TeacherId = 5,
                            courseId = 1010
                        });
                });

            modelBuilder.Entity("WebApplication2.DataAccess.Models.SectionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Section");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Section 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Section 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Section 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Section 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Section 5"
                        });
                });

            modelBuilder.Entity("WebApplication2.DataAccess.Models.SemesterModel", b =>
                {
                    b.Property<int>("SemesterNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterNumber"));

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SemesterNumber");

                    b.ToTable("Semesters");

                    b.HasData(
                        new
                        {
                            SemesterNumber = 1,
                            SemesterName = "First Semester"
                        },
                        new
                        {
                            SemesterNumber = 2,
                            SemesterName = "Second Semester"
                        },
                        new
                        {
                            SemesterNumber = 3,
                            SemesterName = "Summer Semester"
                        });
                });

            modelBuilder.Entity("WebApplication2.DataAccess.Models.StudentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Ramallah",
                            Email = "lina.saeed@example.com",
                            Name = "Lina Saeed",
                            PhoneNumber = "0598765432"
                        },
                        new
                        {
                            Id = 2,
                            City = "Nablus",
                            Email = "omar.nasser@example.com",
                            Name = "Omar Nasser",
                            PhoneNumber = "0599876543"
                        },
                        new
                        {
                            Id = 3,
                            City = "Hebron",
                            Email = "maya.ibrahim@example.com",
                            Name = "Maya Ibrahim",
                            PhoneNumber = "0599987654"
                        },
                        new
                        {
                            Id = 4,
                            City = "Jenin",
                            Email = "hassan.ali@example.com",
                            Name = "Hassan Ali",
                            PhoneNumber = "0599998765"
                        },
                        new
                        {
                            Id = 5,
                            City = "Bethlehem",
                            Email = "dana.mustafa@example.com",
                            Name = "Dana Mustafa",
                            PhoneNumber = "0598887654"
                        },
                        new
                        {
                            Id = 6,
                            City = "Jericho",
                            Email = "sami.fares@example.com",
                            Name = "Sami Fares",
                            PhoneNumber = "0597776543"
                        },
                        new
                        {
                            Id = 7,
                            City = "Gaza",
                            Email = "yara.hani@example.com",
                            Name = "Yara Hani",
                            PhoneNumber = "0596665432"
                        },
                        new
                        {
                            Id = 8,
                            City = "Tulkarm",
                            Email = "nour.adel@example.com",
                            Name = "Nour Adel",
                            PhoneNumber = "0595554321"
                        },
                        new
                        {
                            Id = 9,
                            City = "Qalqilya",
                            Email = "fadi.hassan@example.com",
                            Name = "Fadi Hassan",
                            PhoneNumber = "0594443210"
                        },
                        new
                        {
                            Id = 10,
                            City = "Rafah",
                            Email = "lama.tamer@example.com",
                            Name = "Lama Tamer",
                            PhoneNumber = "0593332109"
                        });
                });

            modelBuilder.Entity("WebApplication2.DataAccess.Models.TeacherModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Ahmad Salem"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Maher Mohammad"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Salma Mostafa"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Rabab Hasan"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Radwan Mahmoud"
                        });
                });

            modelBuilder.Entity("WebApplication2.DataAccess.Models.RegistrationModel", b =>
                {
                    b.HasOne("WebApplication2.DataAccess.Models.SectionCourseModel", "SectionCourse")
                        .WithMany("RegistredStudents")
                        .HasForeignKey("SectionCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication2.DataAccess.Models.SemesterModel", "SemesterModel")
                        .WithMany("Registration")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication2.DataAccess.Models.StudentModel", "Student")
                        .WithMany("RegistredCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectionCourse");

                    b.Navigation("SemesterModel");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("WebApplication2.DataAccess.Models.SectionCourseModel", b =>
                {
                    b.HasOne("WebApplication2.DataAccess.Models.SectionModel", "Section")
                        .WithMany("CourseSection")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication2.DataAccess.Models.TeacherModel", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication2.DataAccess.Models.CourseModel", "course")
                        .WithMany("SectionCourse")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("Teacher");

                    b.Navigation("course");
                });

            modelBuilder.Entity("WebApplication2.DataAccess.Models.CourseModel", b =>
                {
                    b.Navigation("SectionCourse");
                });

            modelBuilder.Entity("WebApplication2.DataAccess.Models.SectionCourseModel", b =>
                {
                    b.Navigation("RegistredStudents");
                });

            modelBuilder.Entity("WebApplication2.DataAccess.Models.SectionModel", b =>
                {
                    b.Navigation("CourseSection");
                });

            modelBuilder.Entity("WebApplication2.DataAccess.Models.SemesterModel", b =>
                {
                    b.Navigation("Registration");
                });

            modelBuilder.Entity("WebApplication2.DataAccess.Models.StudentModel", b =>
                {
                    b.Navigation("RegistredCourses");
                });

            modelBuilder.Entity("WebApplication2.DataAccess.Models.TeacherModel", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
